.gitignore
.vscode/settings.json
package.json
test/cypress.config.js
test/cypress/e2e/api/test.feature
test/cypress/e2e/app/test.feature
test/cypress/fixtures/example.json
test/cypress/support/commands-api.js
test/cypress/support/e2e.js
test/cypress/support/step_definitions/common-api.js
test/cypress/support/step_definitions/common-web.js

Initialization of Cypress plus Cucumber/gherkin style testing to inReach Monorepo.
Issue Number: 
N/A

feat: add cypress

---

.github/workflows/cypress-steps.yml
.github/workflows/sonar-scan.yml
.gitignore
README.md
package.json
pnpm-lock.yaml
sonar-project.properties
test/README.md
test/cypress.config.js
test/cypress/e2e/api/test.feature
test/cypress/fixtures/example.json
test/cypress/support/commands-api.js
test/cypress/support/step_definitions/common-api.js

- Create the steps definitions for API Testing
- Configured Cypress Steps Validations Testing
- Configured SonarCloud configuration (added sonar-project.properties file and yaml file)
- New Features
There was no supported features regarding this.
Issue Number: https://app.asana.com/0/1132189118126148/1203019518000320 
- Create API steps and script to test the steps
- Cypress Steps Validation on PRs as an independent process
- SonarCloud config set up

[Feature] create steps for API testing

---

apps/app/package.json
package.json
packages/config/package.json
packages/eslint-config/package.json
packages/storybook/package.json
packages/types/package.json
packages/ui/package.json
pnpm-lock.yaml

Issue Number: closes #33 
-
-
-

[IN-127] Bump deps to resolve security alerts

---

apps/app/lib/generators/socialMedia.ts
apps/app/public/locales/en/common.json
apps/app/src/data/socialMedia.json
packages/ui/components/core/Button.stories.tsx
packages/ui/components/layout/Footer.tsx
packages/ui/components/layout/UserMenu.tsx
packages/ui/package.json
pnpm-lock.yaml

refactor: switch icon set to FA

---

apps/app/src/pages/_app.tsx
packages/ui/.storybook/font.css
packages/ui/components/layout/SafetyExit.tsx
packages/ui/theme/common.ts
packages/ui/theme/storybook.ts

style: update theme base

---

apps/app/public/locales/en/common.json
packages/ui/components/core/AntiHateMessage.stories.tsx
packages/ui/components/core/AntiHateMessage.tsx
packages/ui/components/core/index.tsx

- Feature
No anti-hate message component does not existent.
Issue Number: [IN-734](https://inreach.atlassian.net/browse/IN-734)
Anti-hate message component added.
[IN-734]: https://inreach.atlassian.net/browse/IN-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: anti-hate

---

.npmrc
apps/app/src/pages/datatest.tsx
packages/ui/components/core/MobileNav.tsx
packages/ui/icon/iconCollection.ts

fix: icon rendering issue

---

packages/ui/components/core/UserReviewSubmit.tsx
packages/ui/modals/Review.stories.tsx
packages/ui/modals/Review.tsx
packages/ui/modals/settings.ts

Review Modal
I created a modal to wrap around the "UserReviewSubmit" component.....
The storybook part is not fully functioning just yet.
Issue Number: IN-782
-
-
-

feat(ui): Review Modal

---

apps/app/public/locales/en/attribute.json
apps/app/public/locales/en/common.json
packages/api/schemas/selects/org.ts
packages/db/prisma/migrations/20230309010125_/migration.sql
packages/db/prisma/schema.prisma
packages/ui/components/core/Badge.tsx
packages/ui/components/sections/Contact.tsx
packages/ui/components/sections/VisitCard.stories.tsx
packages/ui/components/sections/VisitCard.tsx
packages/ui/mockData/locationCard.ts

feat: visit card

---

packages/api/router/organization/queries.ts
packages/api/schemas/selects/org.ts
packages/api/schemas/selects/orgService.ts
packages/db/prisma/migrations/20230313134722_/migration.sql
packages/db/prisma/schema.prisma
packages/db/seed/migrate-v1/org/generator.ts
packages/db/seed/migrate-v1/org/lib/generateKey.ts
packages/ui/mockData/locationCard.ts
packages/ui/mockData/serviceModal.ts
packages/ui/mockData/servicesInfoCard.ts

feat: data updates - add service name

---

packages/api/router/organization/queries.ts
packages/api/schemas/selects/common.ts
packages/api/schemas/selects/org.ts
packages/api/schemas/selects/orgService.ts
packages/ui/mockData/locationCard.ts
packages/ui/mockData/serviceModal.ts
packages/ui/mockData/servicesInfoCard.ts

feat: data updates

---

packages/db/seed/data/12-geodata.ts
packages/db/seed/migrate-v1/idMap.ts
packages/db/seed/migrate-v1/org/generator.ts
packages/db/zod_util/geojson.ts

feat: data seed updates

---

apps/app/src/pages/admin/quicklink/index.tsx

fix: add auth check to quick link landing page

---

apps/app/src/pages/admin/quicklink/email.tsx
apps/app/src/pages/admin/quicklink/phone.tsx
packages/api/router/quicklink.ts

feat: add published col & helpers to quicklink

---

.github/workflows/crowdin.yml
apps/app/src/pages/index.tsx
packages/api/router/quicklink.ts
packages/api/schemas/create/user.ts
packages/auth/lib/cognitoClient.ts
packages/auth/lib/userLogin.ts
packages/aws-user-migrate/Makefile
packages/aws-user-migrate/build.sh
packages/aws-user-migrate/package.json
packages/aws-user-migrate/src/getUser.ts
packages/aws-user-migrate/template.yaml
packages/aws-user-migrate/tsconfig.json
packages/db/prisma/migrations/20230608224620_user_signup_data_field/migration.sql
packages/db/prisma/schema.prisma
packages/ui/components/core/Button.tsx
packages/ui/lib/getTrpcMock.ts
packages/ui/lib/trpcResponse.ts
packages/ui/modals/ForgotPassword.tsx
packages/ui/modals/Login.tsx
packages/ui/modals/SignUp/index.stories.tsx
packages/ui/modals/SignUp/index.tsx

fix: signup/login/reset pw flow

---

packages/ui/modals/AccountVerified.tsx
packages/ui/modals/ClaimOrg.tsx
packages/ui/modals/CreateNewList.tsx
packages/ui/modals/DeleteModal.tsx
packages/ui/modals/ForgotPassword.tsx
packages/ui/modals/Login.tsx
packages/ui/modals/ResetPassword.tsx
packages/ui/modals/Review.tsx

fix: modal sizing on mobile

---

packages/api/schemas/selects/org.ts

Nested query in organizations.byId was missing an 'isPublic' filter for locations.
Issue Number: PLI-18
-
-
-

fix: add "isPublic" filter to locations

---

packages/ui/modals/AccountVerified.tsx
packages/ui/modals/ResetPassword.tsx

Error state was being set based on early results of the zod parse of the url.

fix: account verify/reset password modals

---

apps/app/src/pages/admin/quicklink/services.tsx
apps/app/src/pages/search/intl/[country].tsx
packages/api/lib/errorHandler.ts
packages/api/router/fieldOpt.ts
packages/api/router/service/queries.ts
packages/api/schemas/common.ts
packages/api/schemas/selects/common.ts
packages/api/schemas/selects/location.ts
packages/api/schemas/selects/org.ts
packages/api/schemas/selects/orgService.ts
packages/ui/lib/getTrpcMock.ts
packages/ui/lib/trpcResponse.ts
packages/ui/mockData/suggestOrg.ts
packages/ui/modals/Example.tsx
packages/ui/modals/dataPortal/Attributes/index.tsx
packages/ui/theme/common.tsx
packages/ui/theme/variants/List.ts

fix: filter out crisis service for main listing

---

@types/locale-includes/index.d.ts
apps/app/public/locales/en/common.json
packages/ui/components/core/SearchBox.tsx
packages/ui/package.json
pnpm-lock.yaml

Doing a search where the results include accented characters does not match, even when the results were returned from the API.
Search term: `istan`
Should match: `İstanbul`, `Istán`, etc...
Issue Number: IN-913
Results display as expected.

fix: autocomplete filtering with accented characters

---

.github/workflows/crowdin.yml
apps/app/public/locales/fr/common.json

chore: crowdin action config

---

apps/app/public/.well-known/apple-app-site-association
apps/app/public/.well-known/assetlinks.json
apps/app/src/pages/_app.tsx
packages/ui/components/core/MobileNav.tsx

fix: mobile updates

---

apps/app/src/pages/_app.tsx
apps/app/src/providers/index.tsx
packages/ui/.storybook/main.ts

fix: temp disable cookie banner

---

packages/api/router/user/mutation.create.schema.ts
packages/auth/lib/createUser.ts

fix: lcr signup data

---

packages/ui/components/core/SearchBox.tsx
packages/ui/package.json
pnpm-lock.yaml

fix: escape regex input

---

packages/ui/components/sections/Footer.tsx

feat: edit socials in footer

---

packages/ui/components/sections/Hero.tsx

fix: RevolvingBox translations

---

.prettierrc.js
apps/app/src/pages/admin/quicklink/services.tsx
packages/api/schemas/routes/search.ts
packages/ui/modals/CoverageArea/index.tsx
packages/ui/modals/dataPortal/Attributes/index.tsx

chore: prettier opts & run for new formats

---

apps/app/public/locales/en/common.json
apps/app/src/pages/search/[...params]/index.tsx

feat: search result page alert banner

---

apps/app/next-i18next.config.mjs
apps/app/public/locales/en/common.json
apps/app/src/pages/_app.tsx
apps/app/src/pages/org/[slug]/index.tsx
packages/ui/components/core/Breadcrumb.tsx
packages/ui/components/core/UserAvatar.tsx
packages/ui/components/core/UserMenu.tsx
packages/ui/components/sections/Footer.tsx
packages/ui/components/sections/Navbar.tsx
packages/ui/modals/Service/index.tsx
packages/ui/theme/common.tsx

fix: modal placement/hydration errors

---

apps/app/src/pages/_app.tsx
apps/app/src/pages/search/[...params]/index.tsx

Translations for db based text were not updating on language change.
Issue Number: IN-950
- reverted change from when I was trying to fix hydration errors (passing in i18n config to i18next HOC)
-
-

fix: i18n loading/lang change

---

apps/app/next-i18next.config.mjs
apps/app/sentry.server.config.ts
apps/app/src/pages/api/i18n/load.ts
packages/api/router/service/query.forServiceInfoCard.handler.ts
packages/ui/components/sections/ListingBasicInfo.tsx
packages/ui/components/sections/ServicesInfo.tsx
packages/util/logger/index.ts

fix: i18n loading/service name display

---

.vscode/settings.json
apps/app/.vscode/settings.json
apps/web/.vscode/settings.json
lambdas/.vscode/settings.json
packages/analytics/.vscode/settings.json
packages/api/.vscode/settings.json
packages/auth/.vscode/settings.json
packages/config/.vscode/settings.json
packages/crowdin/.vscode/settings.json
packages/db/.vscode/settings.json
packages/env/.vscode/settings.json
packages/eslint-config/.vscode/settings.json
packages/ui/.vscode/settings.json
packages/util/.vscode/settings.json

chore: sonarlint config

---

packages/ui/components/core/SearchBox.tsx

- If there is an autocomplete item, or several, and you press enter, then the top item is searched for
-
-

feat(app): Search on enter

---

packages/api/router/user/mutation.adminCreate.schema.ts
packages/api/router/user/mutation.confirmAccount.handler.ts
packages/api/router/user/mutation.create.schema.ts
packages/api/router/user/mutation.deleteAccount.handler.ts
packages/api/router/user/mutation.forgotPassword.schema.ts
packages/api/router/user/mutation.resetPassword.handler.ts
packages/auth/lib/changePassword.ts
packages/auth/lib/cognitoJwt.ts
packages/auth/lib/confirmAccount.ts
packages/auth/lib/createUser.ts
packages/auth/lib/deleteAccount.ts
packages/auth/lib/forgotPassword.ts
packages/auth/lib/genUserSession.ts
packages/auth/lib/refreshSession.ts
packages/auth/lib/resendCode.ts
packages/auth/lib/resetPassword.ts
packages/auth/lib/userLogin.ts
packages/auth/providers/cognito.ts

Signup/Login can throw an error due to a case difference in the email address.
- Convert email address to lower case
May need to do a small migration to lowercase all emails in the User table.

fix: convert email to lowercase

---

apps/app/src/pages/search/[...params]/index.tsx

chore: update legislative map url

---

apps/app/next.config.mjs
apps/app/src/pages/org/[slug]/[orgLocationId]/edit.tsx
packages/ui/hooks/useGoogleMapMarker.tsx
packages/ui/hooks/useGoogleMaps.ts
packages/ui/providers/GoogleMaps.tsx
packages/ui/quick-lint-js.config

fix(): excess renders from GoogleMapsProvider

---

apps/app/src/pages/org/[slug]/edit.tsx
packages/db/client/extensions/idGenerator.ts
packages/db/client/extensions/json.ts
packages/db/prisma/data-migrations/2024-01-31_fix-attr-supp-json/index.ts
packages/db/prisma/data-migrations/2024-01-31_target-population-attrib.ts
packages/db/prisma/data-migrations/2024-02-01_add-missing-attributes/index.ts
packages/db/prisma/data-migrations/2024-02-02_deactivate-incompatible-attribs.ts
packages/db/prisma/data-migrations/2024-02-14_attribute-supplement-schemas/index.ts
packages/db/prisma/data-migrations/2024-02-15_attribute-attachments/index.ts
packages/db/prisma/data-migrations/2024-02-19_attach-orphan-text.ts
packages/db/prisma/data-migrations/2024-02-20_appsheet-load/index.ts
packages/db/prisma/data-migrations/2024-02-23_add-missing-website.ts
packages/db/prisma/data-migrations/2024-03-08_update-alerts-and-org-urls/index.ts
packages/db/prisma/data-migrations/2024-03-11_hide-locations.ts
packages/db/prisma/data-migrations/2024-03-15_update-dead-links/index.ts
packages/db/prisma/data-migrations/2024-03-21_attribute-supplement-schemas.ts
packages/db/prisma/data-migrations/2024-04-03_access-instruction-schemas.ts
packages/db/prisma/dataMigrationRunner.ts
packages/db/turbo/generators/templates/dataMigration.hbs
packages/ui/components/sections/ListingBasicInfo.tsx
packages/ui/package.json
pnpm-lock.yaml

Issue Number:
- IN-956
- IN-957
-
-
-

fix: badge display for edits

---

apps/app/src/pages/search/[...params]/index.tsx

chore: update map link url

---

apps/app/public/locales/en/landingPage.json

some language on the landing page is extraneous
This PR updates the text 
from: “Welcome to the world's first open source platform matching TLGBQ+ (transgender, lesbian, gay, bisexual, queer and more identities) people facing persecution or discrimination with safe, verified resources.” 
to: Welcome to the world's first open source verified TLGBQ+ (transgender, lesbian, gay, bisexual, queer and more identities) resource platform.
There is also a slight change under the "Innovative" summary
-
-
-

feat(app): (ECB-72)[https://inreach.atlassian.net/browse/ECB-72]: Update landing page translations.

---

packages/db/prisma/data-migrations/2024-12-22_update-alert-link.ts
packages/db/prisma/data-migrations/index.ts

the anti-trans map link is outdated
updated anti-trans map link with newer data
-
-
-

feat(app): (ECB-63)[https://inreach.atlassian.net/browse/ECB-63]: Update anti-trans risk map link (search results banner alert)

---

packages/db/prisma/data-migrations/2024-12-22_update-alert-link.ts
packages/db/prisma/data-migrations/index.ts

feat(db): (ECB-63)[https://inreach.atlassian.net/browse/ECB-63]: update link for anti-trans map 

---

packages/db/prisma/data-migrations/2025-01-07_update-locationbased-alert-string.ts
packages/db/prisma/data-migrations/index.ts

the current link for erin in the morning is outdated
this migration script updates that link
-
-
-

feat(db): updated migration script for location based alert url link

---

apps/app/src/pages/org/[slug]/[orgLocationId]/edit.tsx
apps/app/src/pages/org/[slug]/[orgLocationId]/index.tsx
apps/app/src/pages/org/[slug]/index.tsx

this PR addresses some TS and lint errors from the previous PR of a similar name
-
-
-

feat(app): ECB-56: temporarily set alertData to empty array so the alert page section is not displayed - fix TS errors

---

apps/app/public/locales/en/services.json
apps/app/public/locales/ht/services.json
packages/db/prisma/data-migrations/2025-01-15_new_food-service-tag.ts
packages/db/prisma/data-migrations/2025-01-15_update-food-tags.ts
packages/db/prisma/data-migrations/index.ts

most of the existing food service options are not selectable when updating org services and offerings
this PR changes the active flag to tru so the services can be configured via a db migration
this PR add a new food service tag called "Hot meals" via db migration as well as an addition to the language file
-
-
-

feat(app): ECB-54: update food service tags, add "Hot meals" tag

---

packages/db/prisma/data-migrations/2025-01-15_update-food-tags.ts

feat(app): ECB-54: update food service tags, use tsKey instead of id

---

packages/db/prisma/data-migrations/2025-01-15_update-cost-tags.ts
packages/db/prisma/data-migrations/index.ts

set these Cost attributes to active:
- “This service accepts insurance” 
- “Costs determined on a sliding scale”
-
-
-

feat(app): ECB-60: update cost attributes to active

---

apps/app/public/locales/en/services.json
apps/app/public/locales/ht/services.json
packages/db/prisma/data-migrations/2025-01-15_new_medical-service-tag.ts
packages/db/prisma/data-migrations/index.ts

Add a new tag under “Medical” category named: “Medical information and referrals”
status is not active, will not appear in front end ui for filtering but will appear on the backend for selection
-
-
-

feat(app): ECB-12: add new tag for medical, create entry in language json file for english

---

apps/app/public/locales/en/services.json
packages/db/prisma/data-migrations/2025-01-29_update-parent-category-for-trans-you-health.ts
packages/db/prisma/data-migrations/index.ts

(1) Update our "Trans health - youth care" tag to be more vague; new tag name = "Trans youth support"  
(2) Move new renamed tag from showing under “Medical” category and just list under the “Mental Health” category (& cross-list under the “Trans Focused Services” category) on the live front-end and in the data portal. 
-
-
-

Feature: Adjust "Trans health - youth care" tag to respond to policy changes (ECB-91)

---

packages/db/prisma/data-migrations/2025-01-29_update-translation-key-for-trans-health-youth.ts
packages/db/prisma/data-migrations/index.ts

needed to update the translation key table as well
-
-
-

Feature: updated translationKet text value as well(ECB-91)

---

packages/db/prisma/data-migrations/2025-01-29_update-nationwide-locationbased-alert.ts
packages/db/prisma/data-migrations/index.ts

secondary alert responding to the Trump admin’s new federal funding / policy changes – language: “Some organizations are adjusting services due to recent funding cuts and policy changes. Contact providers directly for updates.”
change anti-trans map to a secondary alert
-
-
-

feat(app): add alert for trans bans org changes (ECB-90)

---

apps/app/public/locales/en/services.json
packages/db/prisma/data-migrations/2025-01-29_update-nationwide-locationbased-alert.ts
packages/db/prisma/data-migrations/2025-01-29_update-parent-category-for-trans-you-health.ts
packages/db/prisma/data-migrations/2025-01-29_update-translation-key-for-trans-health-youth.ts
packages/db/prisma/data-migrations/index.ts

adjust Trans health youth tag to adjust for US policy changes (ECB-91)
add temporary alert banner (ECB-90)
-
-
-

release: 2025-01-29

---

packages/db/prisma/data-migrations/2025-01-29_update-nationwide-locationbased-alert.ts

feat(app): fix typo in data migration for alert (ECB-90)

---

packages/db/prisma/data-migrations/2025-01-29_update-nationwide-locationbased-alert.ts

release: 2025-01-29a adjust type for db migration for location based alerts

---

apps/app/public/locales/en/attribute.json
packages/db/prisma/data-migrations/2025-02-17_new-cost-attribute.ts
packages/db/prisma/data-migrations/index.ts

feat(app): add new cost attribute

---

packages/db/prisma/data-migrations/2025-02-17_new_legal-service-tag.ts
packages/db/prisma/data-migrations/2025-02-17_new_mental-health-service-tag.ts

feat(app): fix key value for new service tags

---

apps/app/public/locales/en/common.json
apps/app/public/locales/fa/common.json
apps/app/public/locales/ps/common.json

Sign-up header text:
Welcome to the world's first tech platform matching LGBTQ+ people facing persecution or discrimination with safe, verified resources.
Sign-up header text is now set to:
Welcome to the world's first open source verified LGBTQ+ resource platform.
Files which had placeholder text in english have been changed as part of this PR. all other language files will need to be updated via the Crowdin integration.
-
-
-

feat(app): update sign-up header with shorter text

---

apps/app/public/locales/en/common.json
packages/db/prisma/data-migrations/2025-03-05_update-nationwide-locationbased-alert.ts
packages/db/prisma/data-migrations/index.ts
packages/ui/components/core/LocationBasedAlertBanner/index.tsx

change (Erin Reed) to (Erin In The Morning)
alert text “Check out our list of recommended links for trans and immigrant communities” should have the words recommended links underlined, 
'Welcome to the world's first open source verified LGBTQ+ resource platform.' LGBTQ+ dose not need to be bold
-
-
-

feat(app): alert text updates per discourse discussions

---

apps/app/public/locales/en/common.json

feat(app): update erin-in-the-morning (anti-trans) link

---

apps/app/public/locales/en/attribute.json
apps/app/public/locales/en/common.json
packages/db/prisma/data-migrations/2025-03-05_update-attribute-values-asl.ts
packages/db/prisma/data-migrations/2025-03-05_update-attribute-values-lang-inter.ts
packages/db/prisma/data-migrations/index.ts
packages/ui/modals/Service/processor.tsx
packages/ui/modals/Service/processors/langAttrib.ts

release: 2025-03-26

---

packages/ui/components/sections/CrisisSupport/InternationalCard.tsx

release: 2025-04-26 - deploy URL wrap style change

---

apps/app/src/pages/account/saved/[listId].tsx

feat(app): fixing up build errors

---

apps/app/src/pages/account/saved/[listId].tsx

feat(app): fix ts-errors with noImplicitAny error

---

packages/ui/components/core/UserMenu.tsx

fix ts-error is UserMenu

---

apps/app/public/locales/en/common.json
apps/app/src/pages/account/saved/[listId].tsx
apps/app/src/pages/search/intl/index.tsx

feat(app): Clean up changes to finish up the User Management dashboard

---

apps/app/public/locales/en/common.json
apps/app/src/pages/account/saved/[listId].tsx
apps/app/src/pages/admin/management.tsx
apps/app/src/pages/admin/quicklink/email.tsx
apps/app/src/pages/search/intl/index.tsx
apps/app/src/types/nextjs-routes.d.ts
packages/api/lib/middleware/permissions.ts
packages/api/lib/permissions.ts
packages/api/router/user/index.ts
packages/api/router/user/mutation.toggleDataPortalAccess.handler.ts
packages/api/router/user/mutation.toggleDataPortalAccess.schema.ts
packages/api/router/user/query.forUserTable.handler.ts
packages/api/router/user/query.forUserTable.schema.ts
packages/api/router/user/schemas.ts
packages/ui/components/core/Badge/Group.tsx
packages/ui/components/core/Section/Divider.tsx
packages/ui/components/core/UserMenu.tsx
packages/ui/components/data-portal/ManagementTable.stories.tsx
packages/ui/components/data-portal/ManagementTable.tsx
packages/ui/components/data-portal/MultiSelectPopover/hook-form.tsx
packages/ui/components/sections/CrisisSupport/index.stories.tsx
packages/ui/modals/Service/index.tsx
packages/ui/package.json
pnpm-lock.yaml

Push a basic user Management table to production
only users with "@inreach.org" email will have access to this table
-
-
-

chore(release): 2025-07-15 “July B” 

---

apps/app/src/pages/org/[slug]/edit.tsx
packages/api/lib/middleware/permissions.ts
packages/api/router/auditTrail/index.ts
packages/api/router/auditTrail/query.getAllForOrg.handler.ts
packages/api/router/auditTrail/query.getAllForOrg.schema.ts
packages/api/router/auditTrail/schemas.ts
packages/api/router/index.ts
packages/api/router/internalNote/mutation.create.handler.ts
packages/api/router/internalNote/query.getAllForRecord.handler.ts
packages/api/router/internalNote/query.getAllForRecord.schema.ts
packages/api/router/organization/query.forOrgPageEdits.handler.ts
packages/db/prisma/migrations/202500808214500_add_userId_column_internal_note/migration.sql
packages/db/prisma/migrations/20250808_sync_indexes/migration.sql
packages/db/prisma/schema.prisma
packages/ui/components/data-portal/Action.stories.tsx
packages/ui/components/data-portal/Action.tsx
packages/ui/components/data-portal/Activity.stories.tsx
packages/ui/components/data-portal/Activity.tsx
packages/ui/components/data-portal/AuditDrawer.stories.tsx
packages/ui/components/data-portal/AuditDrawer.tsx
packages/ui/components/data-portal/InternalNotesDrawer.stories.tsx
packages/ui/components/data-portal/InternalNotesDrawer.tsx
packages/ui/components/sections/DataToolbar.stories.tsx
packages/ui/components/sections/DataToolbar.tsx

* new components for displaying key dates, auditTrail, and Internal Notes
* create internal note at the organization level
Key Dates displayed on Org Edit page:
* lastUpdated
* lastVerified
* firstPublished
* requires db migration to add a column to the internalnotes table for the note creator

feat(app): Display and Create Internal Notes for an Organization, Display Audit Trail, Display key dates

---

.github/renovate.json
.github/workflows/approve.yml
.github/workflows/cache.yml
.github/workflows/chromatic.yml
.github/workflows/codeql.yml
.github/workflows/crowdin.yml
.github/workflows/labels.yml
.github/workflows/lint.yml
.github/workflows/nextjs_bundle_analysis.yml
.github/workflows/njsscan.yml
.github/workflows/pr-labels.yml
.github/workflows/stale.yml
apps/app/package.json
package.json
packages/api/package.json
packages/ui/components/core/GoogleMap.tsx
packages/ui/components/data-portal/Action.tsx
packages/ui/components/data-portal/InlineTextInput.stories.tsx
packages/ui/components/data-portal/InlineTextInput.tsx
packages/ui/components/data-portal/MultiSelectPopover/hook-form.tsx
packages/ui/components/data-portal/MultiSelectPopover/index.tsx
packages/ui/components/data-portal/MultiSelectPopover/styles.ts
packages/ui/components/data-portal/ServiceEditDrawer/index.tsx
packages/ui/components/data-portal/ServiceSelect/index.tsx
packages/ui/components/sections/ListingBasicInfo.tsx
pnpm-lock.yaml

chore(release): 2025-08-11 "August B"

---

apps/app/src/pages/search/intl/index.tsx
packages/api/router/organization/query.getIntlCrisis.handler.ts

feat(app): change country code placeholder for intl search, update query for intl search
