weareinreach/InReach

packages/ui/components/core/Breadcrumb.stories.tsx
packages/ui/components/core/Breadcrumb.tsx

leverage the shouldUnescape={true} component from Trans 'next-i18next' library so variables, within the translated text, that also contain special characters, will be displayed correctly.
Issue Number: 
https://inreach.atlassian.net/browse/IN-798
-
-
-

bugfix: Properly display special characters in Organization name

---

packages/ui/components/core/ActionButtons.tsx

When not logged in, clicking the "Review" button on an org page would open the review composition modal. User must be logged in to leave a review.
Issue Number: PLI-32
Login prompt modal now shows when not auth'd.

fix: unauthed review click should show login modal

---

apps/app/public/locales/en/services.json
packages/db/prisma/data-migrations/2023-10-25_service-tag-updates.ts
packages/db/prisma/data-migrations/index.ts

chore: service tag data migration

---

packages/api/router/organization/query.getAlerts.handler.ts
packages/db/prisma/data-migrations/2023-12-05_alert-messages.ts
packages/db/prisma/data-migrations/index.ts

Alert messages weren't respecting the "active" flag on attributeSupplements.
-
-
-

fix: alert messages

---

packages/ui/components/sections/Hero.tsx

When switching language, the items inside the `RevolvingBox` component did not translate to the new language.
Issue Number: IN-936
- Call `useTranslation` hook inside component instead of passed as prop.
- It translates!
-

fix: RevolvingBox translations

---

apps/app/public/locales/en/landingPage.json
apps/app/src/pages/index.tsx
packages/ui/components/core/Donate/index.tsx

feat: update banner text, hide donate button on main page

---

apps/app/public/locales/en/common.json
apps/app/src/pages/_app.tsx
apps/app/src/pages/api/i18n/load.ts
apps/app/src/pages/api/trpc/[trpc].ts
apps/app/src/pages/org/[slug]/index.tsx
apps/app/src/utils/i18n.ts
apps/app/src/utils/nsFormatter.ts
packages/api/trpc/ssr.ts
packages/auth/index.browser.ts
packages/auth/index.ts
packages/auth/next-auth/session.browser.ts
packages/auth/next-auth/session.server.ts
packages/auth/package.json
packages/ui/components/core/UserMenu.tsx
packages/ui/components/data-portal/OrganizationTable.tsx
packages/ui/components/sections/ListingBasicInfo.tsx
packages/ui/components/sections/Navbar.tsx

feat: data portal menu item

---

packages/api/router/fieldOpt/index.ts
packages/api/router/fieldOpt/query.attributeCategories.handler.ts
packages/api/router/fieldOpt/query.attributesByCategory.handler.ts
packages/api/router/fieldOpt/query.attributesByCategory.schema.ts
packages/api/router/fieldOpt/query.countries.handler.ts
packages/api/router/fieldOpt/query.countryGovDistMap.handler.ts
packages/api/router/fieldOpt/query.getSubDistricts.handler.ts
packages/api/router/fieldOpt/query.govDists.handler.ts
packages/api/router/fieldOpt/query.govDistsByCountry.handler.ts
packages/api/router/fieldOpt/query.govDistsByCountryNoSub.handler.ts
packages/api/router/fieldOpt/query.languages.handler.ts
packages/api/router/fieldOpt/query.orgBadges.handler.ts
packages/api/router/fieldOpt/query.phoneTypes.handler.ts
packages/api/router/fieldOpt/query.userTitle.handler.ts
packages/api/router/geo/index.ts
packages/api/router/geo/query.autocomplete.handler.ts
packages/api/router/geo/query.geoByPlaceId.handler.ts
packages/api/router/misc/index.ts
packages/api/router/misc/query.forEditNavbar.handler.ts
packages/api/router/misc/query.getCountryTranslation.handler.ts
packages/api/router/misc/query.hasContactInfo.handler.ts
packages/api/router/service/query.forServiceEditDrawer.handler.ts
packages/db/zod_util/attributeSupplement.ts

refactor: api handler cache

---

packages/db/.gitignore
packages/db/prisma/data-migrations/2024-03-08_update-alerts-and-org-urls/index.ts
packages/db/prisma/data-migrations/2024-03-11_hide-locations.ts
packages/db/prisma/data-migrations/index.ts

chore: data migration (urls & misc)

---

apps/app/src/pages/org/[slug]/[orgLocationId]/edit/[orgServiceId].tsx
apps/app/src/pages/org/[slug]/[orgLocationId]/index.tsx
apps/app/src/pages/org/[slug]/index.tsx
apps/app/src/providers/index.tsx
packages/api/router/organization/query.searchDistance.handler.ts
packages/ui/components/core/Badge/Group.tsx
packages/ui/components/core/Badge/Leader.tsx
packages/ui/components/core/Badge/National.tsx
packages/ui/components/core/Badge/styles.ts
packages/ui/components/core/SearchBox.tsx
packages/ui/components/core/SearchResultCard.tsx
packages/ui/modals/MoreFilter.tsx
packages/ui/modals/ServiceFilter/index.tsx

Initial selections for Services/Attributes was trying to be set from the URL params.
Issue Number: IN-946
- Initial selections are now pulled from `searchState`
- Searchbox term set from `searchState`
- Fixed badge styling/using new `Badge` component structure for `SearchResultCard`
- Fixed/cleared misc linting issues

fix: search state navigation carryover

---

packages/db/prisma/data-migrations/2024-03-15_update-dead-links/!schemas.ts
packages/db/prisma/data-migrations/2024-03-15_update-dead-links/index.ts
packages/db/prisma/data-migrations/index.ts

chore: data migration - access links & misc

---

packages/ui/components/core/GoogleMap.stories.tsx
packages/ui/hooks/useGoogleMapMarker.tsx
packages/ui/providers/GoogleMaps.tsx

This small PR slightly refactors a bit of the UI-related code to use the new Marker type from the Google Maps API. The new Marker type has a slightly different implementation from its predecessor; it uses properties where its predecessor used methods instead, so my changes reflect this difference.
No behavior should be modified. The use of new Marker type shouldn't change the behavior. It just uses Google Maps API's new implementation for the Marker. 
Issue Number: 947
There is no new behavior as stated above.
-
-
-

chore: Update Marker type from Google Maps API

---

packages/ui/components/core/SearchBox.tsx

Trying to make the margin a bit better on the clear button
-
-
-
Before:
After:

fix(app): Updated margins

---

apps/app/src/pages/org/[slug]/[orgLocationId]/edit.tsx
apps/app/src/pages/org/[slug]/[orgLocationId]/index.tsx
apps/app/src/pages/org/[slug]/index.tsx

it's not currently possible to edit an alert for an organization. 
an alert can be displayed for an organization or an organization location.
however, this data is extremely outdated.
to temporarily keep these alerts from being displayed in the UI the data alert array has been hardcoded to an empty array.
-
-
-

feat(app): ECB-56: temporarily set alertData to empty array so the alert page section is not displayed

---

apps/app/src/pages/org/[slug]/[orgLocationId]/edit.tsx
apps/app/src/pages/org/[slug]/[orgLocationId]/index.tsx
apps/app/src/pages/org/[slug]/index.tsx

this PR addresses some build automation errors from the previous PR of a similar name
-
-
-

feat(app): ECB-56: temporarily set alertData to empty array so the alert page section is not displayed - fix build automation errors

---

packages/db/prisma/data-migrations/2025-01-29_update-nationwide-locationbased-alert.ts
packages/db/prisma/data-migrations/2025-01-31_remove-twitter-from-SocialMediaServices.ts
packages/db/prisma/data-migrations/2025-01-31_remove-twitter-from-orgWebsite-and-OrgSocialMedia.ts
packages/db/prisma/data-migrations/index.ts
packages/ui/components/core/SocialLink.stories.tsx
packages/ui/components/core/SocialLink.tsx
packages/ui/components/sections/Footer.tsx

currently if an organization has a Twitter or X link defined that link will appear in the socials section of the organization data
when orgs are created or edited it's possible to add twitter or X  social media links
made code changes so any of InReaches twitter/X details no longer appear within the app
made some data migrations to unpublish twitter/x data for any org
made some data migrations to remove twitter from the socials drop down so it can no longer be added to an org
the rest of the ticket, to add new values still needs to be completed as this will require additional language translations.
-
-
-

feat(app): remove Twitter/X as an option under Socials (ECB-67)

---

packages/db/prisma/data-migrations/2025-01-29_update-nationwide-locationbased-alert.ts
packages/db/prisma/data-migrations/2025-01-31_remove-twitter-from-SocialMediaServices.ts
packages/db/prisma/data-migrations/2025-01-31_remove-twitter-from-orgWebsite-and-OrgSocialMedia.ts
packages/db/prisma/data-migrations/index.ts
packages/ui/components/core/SocialLink.stories.tsx
packages/ui/components/core/SocialLink.tsx
packages/ui/components/sections/Footer.tsx

release: 2025-02-01 

---

.github/autoapprove-config.yaml
packages/ui/components/core/Badge/Claimed.tsx

Organizations have badges which indicate if they have been claimed or not. The badge display is correct but the ability to claim an organization is not yet functional.
With this PR, the badges are replaced with a Coming soon link, which when clicked explains the claim and unclaimed details. the modal indicates that the feature is not yet available.
-
-
-

feat(app): replace Claimed and Unclaimed badge with Coming soon link

---

apps/app/public/locales/en/attribute.json
packages/db/prisma/data-migrations/2025-03-05_update-attribute-values-asl.ts
packages/db/prisma/data-migrations/2025-03-05_update-attribute-values-lang-inter.ts
packages/db/prisma/data-migrations/index.ts
packages/ui/modals/Service/processor.tsx
packages/ui/modals/Service/processors/langAttrib.ts

feat(app): update language options for sign language options, fix language picker bug for sign language options

---

apps/app/public/locales/en/common.json
apps/app/public/locales/uk/common.json
apps/app/src/pages/search/intl/index.tsx

There is no route support for a generic international landing page at search/intl
users must search based on a country first
this PR provides a basic route for /search/intl which brings users to a basic international landing page. 
the title reads "InReach only operates in North America." then lists information for a few international resources.
-
-
-

feat(app): ECB-101 added support for search/intl/ route

---

packages/ui/components/sections/CrisisSupport/InternationalCard.tsx

on the international support page /search/intl/{country}, website URLs would wrao but could still be too long for the parent container, depending on the device size used to view the results. i.e mobile.
added some inline styles to ensure the url link would wrap based on the size of the parent div container
-
-
-

bugfix(app): ensure long url links wrap on the International page info cards
